/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: 'var(--color-ink)',
        'ink-black': 'var(--color-ink-black)',
        'paper-canvas': 'var(--color-paper-canvas)',
        'cloud-canvas': 'var(--color-cloud-canvas)',
        'paper-white': 'var(--color-paper-white)',
        brand: {
          DEFAULT: 'var(--color-brand)',
          light: 'var(--color-brand-light)',
          dark: 'var(--color-brand-dark)',
          muted: 'var(--color-brand-muted)',
        },
        'fire-orange': 'var(--color-brand)',
        'code-blue': 'var(--color-brand)',
        'canvas-warm': 'var(--color-canvas-warm)',
        'marketing-orange': 'var(--color-fire-orange)',
        'off-black': 'var(--color-off-black)',
        'pale-stone': 'var(--color-pale-stone)',
        'pale-ash': 'var(--color-frost-gray)',
        'frosted-gray': 'var(--color-cloud-canvas)',
        'frost-gray': 'var(--color-frost-gray)',
        'slate-gray': 'var(--color-slate-gray)',
        'stone-gray': 'var(--color-stone-gray)',
        'silver-mist': 'var(--color-silver-mist)',
        'lead-gray': 'var(--color-slate-gray)',
        'canvas-white': 'var(--color-cloud-canvas)',
        'whisper-gray': 'var(--color-whisper-gray)',
        'atmosphere-wash': 'var(--color-atmosphere-wash)',
        surface: 'var(--color-surface)',
        card: 'var(--color-card)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        accent: 'var(--color-accent)',
        'segment-track': 'var(--color-segment-track)',
        'accent-violet': 'var(--color-code-blue)',
      },
      fontFamily: {
        ui: 'var(--font-ui)',
        body: 'var(--font-body)',
        display: 'var(--font-display)',
        sans: 'var(--font-sans)',
        stat: ['var(--font-stat)', { fontVariantNumeric: 'tabular-nums' }],
        data: ['var(--font-ui)', { fontVariantNumeric: 'tabular-nums' }],
        mono: 'var(--font-mono)',
      },
      fontSize: {
        caption: ['var(--text-caption)', { lineHeight: 'var(--leading-caption)' }],
        'body-sm': ['var(--text-body-sm)', { lineHeight: 'var(--leading-body-sm)' }],
        body: ['var(--text-body)', { lineHeight: 'var(--leading-body)' }],
        'body-lg': ['var(--text-body-lg)', { lineHeight: 'var(--leading-body-lg)' }],
        subheading: ['var(--text-subheading)', { lineHeight: 'var(--leading-subheading)' }],
        'heading-sm': ['var(--text-heading-sm)', { lineHeight: 'var(--leading-heading-sm)' }],
        heading: ['var(--text-heading)', { lineHeight: 'var(--leading-heading)' }],
        'heading-lg': ['var(--text-heading-lg)', { lineHeight: 'var(--leading-heading-lg)' }],
      },
      borderRadius: {
        bubble: 'var(--radius-bubble)',
        card: 'var(--radius-card)',
        pill: 'var(--radius-pill)',
        button: 'var(--radius-button)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        input: 'var(--shadow-input)',
        md: 'var(--shadow-md)',
        card: 'var(--shadow-card)',
        elevated: 'var(--shadow-xl-3)',
        'xl-2': 'var(--shadow-xl-2)',
      },
      maxWidth: {
        page: 'var(--page-max-width)',
      },
    },
  },
  plugins: [],
}
